#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage: run_sensitivity_regression_check.sh <binary> <case_file>" >&2
    exit 2
fi

binary="$1"
case_file="$2"
case_name="$(basename "$case_file")"

# This script is shared by both tiers of the sensitivity regression lane
# (see CMakeLists.txt). The fast tier sets
# NEKO_TOP_RUN_SENSITIVITY_REGRESSION=1 in its own test command, so it
# always passes the check below. The slow tier inherits the caller's
# environment: unset (or empty) NEKO_TOP_RUN_SENSITIVITY_REGRESSION means
# "skip", matching how run_valgrind_check.sh skips when the `valgrind` tool
# itself is absent, but here the gate is an explicit choice rather than a
# tool-availability check.
if [[ -z "${NEKO_TOP_RUN_SENSITIVITY_REGRESSION:-}" ]]; then
    echo "Skipping sensitivity regression test: set" \
        "NEKO_TOP_RUN_SENSITIVITY_REGRESSION=1 to opt in (the slow tier is" \
        "not part of the default test budget)."
    exit 77
fi

if [[ ! -x "$binary" ]]; then
    echo "Executable not found or not executable: $binary" >&2
    exit 2
fi

if [[ ! -f "$case_file" ]]; then
    echo "Required case file not found: $case_file" >&2
    exit 2
fi

cp -f "$case_file" "$case_name"

mesh_n="${NEKO_TOP_SENSITIVITY_MESH_N:-8}"
nx=$((mesh_n * 2))
ny=$mesh_n
nz=1
z=$(python3 -c "print(1.0 / ${mesh_n})")

# Reuse a mesh already generated by an earlier case in this same (locked)
# working directory, to avoid regenerating it once per case.
if [[ ! -f box.nmsh ]]; then
    echo "Generating mesh: ${nx} ${ny} ${nz}"
    genmeshbox 0 2 0 1 0 "$z" "$nx" "$ny" "$nz" .false. .true. .true.
fi

ranks="${NEKO_TOP_SENSITIVITY_RANKS:-2}"
export NEKO_LOG_FILE="neko_${case_name%.*}.log"

# The FD-vs-analytic tolerance assertion happens inside the driver itself
# (shared `sensitivity` module, see tests/shared/sensitivity.f90) —
# a non-zero exit here means the finite-difference check genuinely failed,
# not just that something crashed.
mpirun -n "$ranks" "$binary" "$case_name"

echo "Sensitivity regression check passed for ${case_name}."
