name: Setup the GSLib library
description: |
  This action sets up the GSLib library for use in the main workflow.
  Note that the GSLib library is pulled from Nek5000's fork of the GSLib
  library.

# ---------------------------------------------------------------------------- #
# Define the inputs and outputs for this action. The inputs are used to
# configure the action, while the outputs are used to pass information
# back to the caller.

inputs:
  install-dir:
    description: "The directory to install the GSLib library."
    required: false
    default: "/home/runner/pkg/gslib"

  working-dir:
    description: "The directory to work in."
    required: false
    default: "/home/runner/tmp/gslib"

  os:
    description: "The operating system to use."
    required: false
    default: "${{ runner.os }}"

  build-options:
    description: "The build option to use."
    required: false
    default: "--parallel $(nproc)"

  version:
    description: "The version of the GSLib library to use."
    required: false
    default: "v1.0.8"

outputs:
  install-dir:
    description: "The directory where the GSLib library was installed."
    value: ${{ steps.set-output.outputs.install-dir }}

# ---------------------------------------------------------------------------- #
# Define the steps that will be run in this action.

runs:
  using: composite
  steps:
    # ------------------------------------------------------------------------ #
    # Setup the cache for the GSLib library and clone the repository.

    - name: Create cache key based on version, OS, and compiler
      id: create-key
      shell: bash
      env:
        VERSION: ${{ inputs.version }}
        OS: ${{ inputs.os }}
        COMPILER: ${{ inputs.compiler }}
        COMPILER_FLAGS: ${{ inputs.compiler-flags }}
        REPO: https://github.com/Nek5000/gslib.git
      run: |
        # Get the GIT sha for the current commit
        SHA=$(git ls-remote $REPO $VERSION | awk '{print $1}')
        key="gslib-$SHA-$OS-$COMPILER-${COMPILER_FLAGS// /_}"
        printf "key=%s\n" "$key" | tee -a $GITHUB_OUTPUT

    - name: Cache
      id: cache-gslib
      uses: actions/cache@v5
      with:
        path: ${{ inputs.install-dir }}
        key: ${{ steps.create-key.outputs.key }}

    - name: Clone
      if: ${{ steps.cache-gslib.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        WORKING_DIR: ${{ inputs.working-dir }}
        REPO: https://github.com/Nek5000/gslib.git
        VERSION: ${{ inputs.version }}
      run: |
        git clone --depth 1 --branch $VERSION $REPO $WORKING_DIR
        cd $WORKING_DIR

    # ------------------------------------------------------------------------ #
    # Setup the system for building the GSLib library

    - name: Install dependencies
      # if: ${{ steps.cache-pfunit.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        sudo apt install openmpi-bin liblapack-dev libopenmpi-dev libopenblas-dev

    # ------------------------------------------------------------------------ #
    # Configure, build, and install the GSLib library.

    - name: Build
      if: ${{ steps.cache-gslib.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        WORKING_DIR: ${{ inputs.working-dir }}
        INSTALL_DIR: ${{ inputs.install-dir }}
      run: |
        cd $WORKING_DIR
        make CC=mpicc DESTDIR=$INSTALL_DIR -j

    - name: Install
      if: ${{ steps.cache-gslib.outputs.cache-hit != 'true' }}
      shell: bash
      env:
        WORKING_DIR: ${{ inputs.working-dir }}
        INSTALL_DIR: ${{ inputs.install-dir }}
      run: |
        cd $WORKING_DIR
        make CC=mpicc DESTDIR=$INSTALL_DIR install

    # ------------------------------------------------------------------------ #
    # Cleanup the working directory if necessary and set the output.

    - name: Set output
      shell: bash
      id: set-output
      run: |
        echo "install-dir=$(echo ${{ inputs.install-dir }})" >> $GITHUB_OUTPUT
