#!/usr/bin/bash

# ============================================================================ #
# Define the help function
mpirun -np 14 ./neko perturbation_simcomp.case
# End of file
# ============================================================================ #
