# This workflow checks the compilation of the Neko-TOP library.

name: Scripting Checks

# This workflow is only defined here. It is triggered from other workflows.
on:
  workflow_call:
    inputs:
      json-fortran-version:
        description: "The version of json-fortran to use."
        required: true
        type: string
      neko-version:
        description: "The version of Neko to use."
        required: true
        type: string

# ---------------------------------------------------------------------------- #
# Define the jobs that will be run in this workflow. The jobs are run in a

jobs:

  # -------------------------------------------------------------------------- #
  # Define the compilation and testing job that will be run in this workflow.
  # This job will build the Neko-TOP code in debug mode and run the unit tests.

  setup-script:
    name: Check setup script
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------------- #
      # Checkout the repository and setup the environment
      # ---------------------------------------------------------------------- #

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get system cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openmpi-bin pkg-config liblapack-dev ninja-build
          version: 1.0

      - name: Setup non-cache dependencies
        run: sudo apt-get install -y libopenblas-dev libopenmpi-dev

      # ---------------------------------------------------------------------- #
      # Build and test the code
      # ---------------------------------------------------------------------- #

      - name: Setup Neko-TOP
        run: ./setup.sh --examples

      - name: Run TGV
        run: ./run.sh -nrc tgv

      - name: Run Rugby Ball
        run: |
          # Adjust the end time and max iterations for the rugby ball case
          sed -i -r 's/"end_time":.*/"end_time": 1e-3,/g' examples/rugby_ball/rugby_ball.case
          sed -i -r 's/"max_iterations":.*/"max_iterations": 2,/g' examples/rugby_ball/rugby_ball.case

          ./run.sh -rc rugby_ball

  setup-action:
    name: Check setup action
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------------- #
      # Checkout the repository and setup the environment
      # ---------------------------------------------------------------------- #

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get json-fortran
        id: get-json-fortran
        uses: ./.github/actions/setup_json-fortran
        with:
          version: ${{ inputs.json-fortran-version }}

      - name: Get neko
        id: get-neko
        uses: ./.github/actions/setup_neko
        with:
          json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}
          version: ${{ inputs.neko-version }}

      - name: Get neko-top
        id: get-neko-top
        uses: ./.github/actions/setup_neko-top
        with:
          version: ${{ github.ref_name }}
          neko-dir: ${{ steps.get-neko.outputs.install-dir }}
          json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}

      - name: Run TGV
        env:
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
        run: ./run.sh -nrc tgv

      - name: Run Rugby Ball
        env:
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
        run: |
          # Adjust the end time and max iterations for the rugby ball case
          sed -i -r 's/"end_time":.*/"end_time": 1e-3,/g' examples/rugby_ball/rugby_ball.case
          sed -i -r 's/"max_iterations":.*/"max_iterations": 2,/g' examples/rugby_ball/rugby_ball.case

          ./run.sh -rc rugby_ball