# This check is used to ensure documentation can be built from the main branch.
name: Check documentation

on:
  # This workflow is only defined here. It is triggered from other workflows.
  workflow_call:

jobs:
  test_documentation:
    name: Check documentation
    runs-on: ubuntu-latest
    steps:
      - name: Setup system
        shell: bash
        run: |
          sudo apt install git cmake doxygen graphviz

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure documentation
        run: |
          cmake -DONLY_DOCS=ON -B build -S .

      - name: Build documentation
        run: |
          cmake --build build --target Documentation
