# This workflow checks the compilation of the Neko-TOP library.

name: Check Neko-TOP compilation

# This workflow is only defined here. It is triggered from other workflows.
on:
  workflow_call:
    inputs:
      neko-version:
        description: "The version of Neko to use."
        required: true
        type: string
      json-fortran-version:
        description: "The version of json-fortran to use."
        required: true
        type: string

# ---------------------------------------------------------------------------- #
# Define the jobs that will be run in this workflow. The jobs are run in a

jobs:

  # -------------------------------------------------------------------------- #
  # Define the compilation and testing job that will be run in this workflow.
  # This job will build the Neko-TOP code in debug mode and run the unit tests.

  neko-top-debug:
    name: Compile Neko-TOP
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------------- #
      # Checkout the repository and setup the environment
      # ---------------------------------------------------------------------- #

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get system cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openmpi-bin pkg-config liblapack-dev ninja-build
          version: 1.0

      - name: Setup non-cache dependencies
        shell: bash
        run: |
          sudo apt-get install -y libopenblas-dev libopenmpi-dev

      # ---------------------------------------------------------------------- #
      # Setup the external dependencies
      # ---------------------------------------------------------------------- #

      - name: Get json-fortran
        id: get-json-fortran
        uses: ./.github/actions/setup_json-fortran
        with:
          version: ${{ inputs.json-fortran-version }}

      - name: Get neko
        id: get-neko
        uses: ./.github/actions/setup_neko
        with:
          json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}
          version: ${{ inputs.neko-version }}

      # ---------------------------------------------------------------------- #
      # Build and test the code
      # ---------------------------------------------------------------------- #

      - name: Configuration
        env:
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
        run: |
          cmake -B build -S . -G Ninja --fresh \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=ON \
            -DJSON_FORTRAN_DIR=$JSON_FORTRAN_DIR \
            -DNEKO_DIR=$NEKO_DIR

      - name: Building Library
        run: |
          cmake --build build --parallel

      - name: Running Unit Tests
        run: |
          ctest --test-dir build --output-on-failure --parallel -L "Unit"

      # ---------------------------------------------------------------------- #
      # Run a rugby ball example to ensure everything works as expected
      # ---------------------------------------------------------------------- #

      - name: Building Examples
        run: |
          cmake --build build --target Examples --parallel

      - name: Run Rugby Ball
        env:
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
        run: |
          # Adjust the end time and max iterations for the rugby ball case
          sed -i -r 's/"end_time":.*/"end_time": 1e-3,/g' examples/rugby_ball/rugby_ball.case
          sed -i -r 's/"max_iterations":.*/"max_iterations": 2,/g' examples/rugby_ball/rugby_ball.case

          ./run.sh -rc rugby_ball

      # ---------------------------------------------------------------------- #
      # Report errors if any step fails
      # ---------------------------------------------------------------------- #
      - name: Report errors
        if: failure()
        run: |
          echo "Errors encountered during script execution. Please check the logs for details."
          logs=($(find logs/ -name "error.log"))

          for file in ${logs[@]}; do
            if [[ -s $file ]]; then
              printf "\nContents of $file:\n" >&2
              cat $file >&2
            elif [ -f $file ]; then
              rm -fr $(dirname $file)
            fi
          done

      - name: Save logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-compile-logs
          path: logs/**/*.log
          overwrite: true
