# This check is used to ensure documentation can be built from the main branch.

name: Formatting

on:
  pull_request:
    branches: [main, develop]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup system
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install findent
      - name: Format
        run: |
          export FINDENT_FLAGS="-Rr -i2 -d3 -f3 -s3 -w3 -t3 -j3 -kd --ws_remred --align_paren --indent_ampersand"
          find sources/ -name "*.f90" -exec bash -c "findent < \"{}\" > \"{}\".tmp && mv -f \"{}\".tmp \"{}\"" \;
      - name: Check format
        run: |
          git diff --exit-code
