# This workflow checks the compilation of the Neko-TOP library.

name: Check Neko-TOP compilation

# This workflow is only defined here. It is triggered from other workflows.
on:
  workflow_call:
    inputs:
      neko-version:
        description: "The version of Neko to use."
        required: true
        type: string
      json-fortran-version:
        description: "The version of json-fortran to use."
        required: true
        type: string
      pfunit-version:
        description: "The version of pFUnit to use."
        required: true
        type: string
      hdf5-version:
        description: "The version of HDF5 to use."
        required: true
        type: string

# ---------------------------------------------------------------------------- #
# Define the jobs that will be run in this workflow. The jobs are run in a

jobs:
  # -------------------------------------------------------------------------- #
  # Define the compilation and testing job that will be run in this workflow.
  # This job will build the Neko-TOP code in debug mode and run the unit tests.

  neko-top-debug:
    # ------------------------------------------------------------------------ #
    # Define the Matrix for the job.
    # ------------------------------------------------------------------------ #

    strategy:
      fail-fast: false
      matrix:
        # Default matrix
        precision: [dp]
        backend: [CPU, CUDA, HIP]
        compiler: [GNU-13, GNU-14]

        # Define the setup jobs
        include:
          - compiler: GNU-13
            setup-compiler: |
              echo "c-compiler=gcc-13" >> $GITHUB_OUTPUT
              echo "f-compiler=gfortran-13" >> $GITHUB_OUTPUT

          - compiler: GNU-14
            setup-compiler: |
              echo "c-compiler=gcc-14" >> $GITHUB_OUTPUT
              echo "f-compiler=gfortran-14" >> $GITHUB_OUTPUT

          - backend: CUDA
            setup-backend: |
              echo "backend-path=/usr" >> $GITHUB_OUTPUT

          - backend: HIP
            setup-backend: |
              ROCM_DIR=$(ls -d /opt/rocm-*)
              CMAKE_PREFIX_PATH="$ROCM_DIR/lib/cmake:$CMAKE_PREFIX_PATH"
              echo "CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
              echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROCM_DIR/lib" >> $GITHUB_ENV
              echo "backend-path=$ROCM_DIR" >> $GITHUB_OUTPUT

    # ------------------------------------------------------------------------ #
    # Define the job itself.
    # ------------------------------------------------------------------------ #
    name: ${{ matrix.backend }} - ${{ matrix.compiler }} - ${{ matrix.precision }}
    runs-on: ubuntu-latest
    env:
      JOB_NAME: ${{ matrix.backend }}-${{ matrix.compiler }}-${{ matrix.precision }}
    steps:
      # ---------------------------------------------------------------------- #
      # Checkout the repository and setup the environment
      # ---------------------------------------------------------------------- #

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Compiler
        id: setup-compiler
        shell: bash
        run: ${{ matrix.setup-compiler }}

      - name: Setup system dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libopenblas-dev libopenmpi-dev \
            openmpi-bin pkg-config liblapack-dev ninja-build

      # Setup device specific dependencies
      - name: Setup Device (CUDA)
        if: matrix.backend == 'cuda'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: nvidia-cuda-toolkit
          version: cuda-cache-1.0

      - name: Setup Device (HIP) - install rocm-dev
        if: matrix.backend == 'hip'
        run: |
          # Following the instructions from https://rocm.docs.amd.com/projects/install-on-linux/en/latest/install/quick-start.html

          wget -r -np -nd -A 'amdgpu*.deb' https://repo.radeon.com/amdgpu-install/7.2.1/ubuntu/noble/
          sudo apt install ./amdgpu-install_*.deb
          sudo apt update
          sudo apt install -y rocm-dev

      - name: Setup Device (HIP) - install amdgpu-dkms
        if: matrix.backend == 'hip'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: amdgpu-dkms hipsolver-dev hipblas-dev
          version: hip-cache-1.0

      - name: Setup backend
        id: setup-backend
        shell: bash
        run: ${{ matrix.setup-backend }}

      # ---------------------------------------------------------------------- #
      # Setup the external dependencies
      # ---------------------------------------------------------------------- #

      - name: Get json-fortran
        id: get-json-fortran
        uses: ./.github/actions/setup_json-fortran
        with:
          version: ${{ inputs.json-fortran-version }}
          compiler: ${{ steps.setup-compiler.outputs.f-compiler }}

      - name: Get ParMETIS
        id: get-parmetis
        uses: ./.github/actions/setup_parmetis
        with:
          compiler: ${{ steps.setup-compiler.outputs.f-compiler }}

      - name: Get HDF5
        id: get-hdf5
        uses: ./.github/actions/setup_hdf5
        with:
          version: ${{ inputs.hdf5-version }}
          compiler: ${{ steps.setup-compiler.outputs.f-compiler }}
          c-compiler: ${{ steps.setup-compiler.outputs.c-compiler }}

      - name: Get neko
        id: get-neko
        uses: ./.github/actions/setup_neko
        with:
          json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}
          parmetis-dir: ${{ steps.get-parmetis.outputs.install-dir }}
          hdf5-dir: ${{ steps.get-hdf5.outputs.install-dir }}
          version: ${{ inputs.neko-version }}
          precision: ${{ matrix.precision }}
          compiler: ${{ steps.setup-compiler.outputs.f-compiler }}
          backend: ${{ matrix.backend }}
          backend-path: ${{ steps.setup-backend.outputs.backend-path }}

      - name: Get pfunit
        id: get-pfunit
        uses: ./.github/actions/setup_pfunit
        with:
          version: ${{ inputs.pfunit-version }}

      # ---------------------------------------------------------------------- #
      # Build and test the code
      # ---------------------------------------------------------------------- #

      - name: Configuration
        env:
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          PFUNIT_DIR: ${{ steps.get-pfunit.outputs.install-dir }}
          HDF5_ROOT: ${{ steps.get-hdf5.outputs.install-dir }}
        run: |
          if [ "${{ matrix.backend }}" == "CPU" ]; then
            TEST=ON
          else
            TEST=OFF
          fi
          cmake -B build -S . -G Ninja --fresh \
            -DCMAKE_BUILD_TYPE=Debug \
            -DBUILD_TESTING=$TEST

      - name: Building Library
        run: |
          cmake --build build --parallel

      # ---------------------------------------------------------------------- #
      # Run the tests, which is only done on the CPU backend as the github
      # runner does not have a GPU available.
      # ---------------------------------------------------------------------- #

      - name: Running Unit Tests
        if: ${{ matrix.backend == 'cpu' }}
        run: |
          ctest -L unit --test-dir build --output-on-failure --parallel

      - name: Building Examples
        if: ${{ matrix.backend == 'cpu' }}
        run: |
          cmake --build build --target Examples --parallel

      - name: Run Rugby Ball
        if: ${{ matrix.backend == 'cpu' }}
        env:
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
          PARMETIS_DIR: ${{ steps.get-parmetis.outputs.install-dir }}
          HDF5_DIR: ${{ steps.get-hdf5.outputs.install-dir }}
        run: |
          # Adjust the end time and max iterations for the rugby ball case
          sed -i -r 's/"end_time":.*/"end_time": 1e-3,/g' examples/rugby_ball/rugby_ball.case
          sed -i -r 's/"max_iterations":.*/"max_iterations": 2,/g' examples/rugby_ball/rugby_ball.case

          ./run.sh -rc rugby_ball

      # ---------------------------------------------------------------------- #
      # Report errors if any step fails
      # ---------------------------------------------------------------------- #
      - name: Report errors
        if: failure()
        run: |
          [ ! -d logs ] && exit
          echo "Errors encountered during script execution."
          echo "Please check the logs for details."
          logs=($(find logs/ -name "error.log"))

          for file in ${logs[@]}; do
            if [[ -s $file ]]; then
              printf "\nContents of $file:\n" >&2
              cat $file >&2
            elif [ -f $file ]; then
              rm -fr $(dirname $file)
            fi
          done

      - name: Save logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.JOB_NAME }}-logs
          path: logs/
          overwrite: true
          if-no-files-found: ignore
