# This workflow checks the compilation of the Neko-TOP library.

name: Check Neko-TOP compilation script

# This workflow is only defined here. It is triggered from other workflows.
on:
  workflow_call:
    inputs:
      neko-version:
        description: "The version of Neko to use."
        required: true
        type: string
      json-fortran-version:
        description: "The version of json-fortran to use."
        required: true
        type: string

# ---------------------------------------------------------------------------- #
# Define the jobs that will be run in this workflow. The jobs are run in a

jobs:

  # -------------------------------------------------------------------------- #
  # Define the compilation and testing job that will be run in this workflow.
  # This job will build the Neko-TOP code in debug mode and run the unit tests.

  neko-top-debug:
    name: Compile Neko-TOP
    runs-on: ubuntu-latest

    steps:
      # ---------------------------------------------------------------------- #
      # Checkout the repository and setup the environment
      # ---------------------------------------------------------------------- #

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get system cache
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: openmpi-bin pkg-config liblapack-dev ninja-build
          version: 1.0

      - name: Setup non-cache dependencies
        shell: bash
        run: |
          sudo apt-get install -y libopenblas-dev libopenmpi-dev

      # ---------------------------------------------------------------------- #
      # Build and test the code
      # ---------------------------------------------------------------------- #

      - name: Setup Neko-TOP
        shell: bash
        run: ./setup.sh

      - name: Run TGV test
        shell: bash
        run: ./run.sh -nrc tgv
