name: Linting

# Controls when the action will run.
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - ci/*

jobs:
  lint-develop:
    name: "Lint develop branch"
    runs-on: ubuntu-20.04
    outputs:
      score: ${{ steps.save-score.outputs.score }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: develop

      - name: Run flint
        id: lint
        uses: ./.github/actions/flint
        with:
          path: sources/
          depth: 10
          rc-file: flinter_rc.yml

      - name: Save the score
        id: save-score
        run: |
          echo "Develop score=${{ steps.lint.outputs.score }}"
          echo "score=${{ steps.lint.outputs.score }}" >> $GITHUB_OUTPUT

  lint-current:
    name: "Lint current branch"
    runs-on: ubuntu-20.04
    outputs:
      score: ${{ steps.save-score.outputs.score }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Lint repository
        id: lint
        uses: ./.github/actions/flint
        with:
          path: sources/ examples/ tests/
          depth: 10
          rc-file: flinter_rc.yml

      - name: Save the score
        id: save-score
        run: |
          echo "Current score=${{ steps.lint.outputs.score }}"
          echo "score=${{ steps.lint.outputs.score }}" >> $GITHUB_OUTPUT

  check-scores:
    name: "Check scores"
    runs-on: ubuntu-20.04
    needs:
      - lint-develop
      - lint-current

    steps:
      # Check if the current branch has a lower score than the develop branch.
      # If it does, we will lint the changed files.
      # If it doesn't, we will skip the linting.
      - name: Check the scores
        id: check-score
        env:
          develop_score: ${{ needs.lint-develop.outputs.score }}
          current_score: ${{ needs.lint-current.outputs.score }}
        run: |
          if [ -z "$develop_score" ]; then
            echo "Develop score not set: '$develop_score'" >&2
            exit 1
          fi
          if [ -z "$current_score" ]; then
            echo "Current score not set: '$current_score'" >&2
            exit 1
          fi

          if (($(echo "$current_score < $develop_score" | bc -l))); then
            echo "Linting failed, the score is lower than the develop branch."
            echo "Please improve linting by applying suggestions."
            exit 2
          fi

  lint-changed-files:
    name: "Lint changed files"
    runs-on: ubuntu-20.04
    needs:
      - lint-develop
      - lint-current

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

        # Get a list of the changed files and store them for later use.
      - name: Get changed files
        id: get-changed-files
        run: |
          git fetch --unshallow origin develop
          changes=($(git diff --name-only --diff-filter=d origin/develop))

          printf "Detected fortran changes:\n"
          for file in ${changes[@]}; do
            if [[ ${file: -4} != ".f90" && ${file: -4} != ".F90" ]]; then
              continue
            fi
            printf "\t- $file\n"
          done

          echo "changed-files=${changes[@]}" >> $GITHUB_OUTPUT

      - name: Report possible improvements
        uses: ./.github/actions/flint
        with:
          path: ${{ steps.get-changed-files.outputs.changed-files }}
          rc-file: flinter_rc.yml

  # Create a badge for the flint score
  create-badge-lint:
    name: "Create linting badge"
    runs-on: ubuntu-20.04
    needs:
      - lint-current

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup env.
        run: |
          sudo apt-get update
          sudo apt-get install -yq python3-pip
          pip install anybadge

      - name: Create badge
        env:
            score: ${{ needs.lint-current.outputs.score }}
        run: |
            mkdir -p doc/media
            anybadge -l Flint -o --file=doc/media/lint-badge.svg -v $score 9.0=red 9.9=yellow 10=green

      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: lint-badge
          path: doc/media/lint-badge.svg