# Check the formatting of source files
#
# This workflow checks the formatting of the source files in the repository. It
# uses the `findent` tool to format the Fortran source files. This allow us to
# enforce rather strickt formatting rules.

name: Check Formatting

on:
  # Allow the workflow to be called from other workflows.
  # This is useful when we want to run the workflow on a specific event.
  workflow_call:

jobs:
  check-formatting:
    name: Check the formatting of source files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup python cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements-formatting.txt"

      - name: Install requirements
        run: |
          pip install -r .github/workflows/extra/requirements-formatting.txt

      - name: Format sources
        env:
          FINDENT_FLAGS: ${{ vars.FINDENT_FLAGS }}
        run: |
          find sources/ -name "*.f90" -type f -exec bash -c \
            "findent < \"{}\" > \"{}\".tmp && mv -f \"{}\".tmp \"{}\"" \;

      - name: Check format
        run: |
          git diff --exit-code
