# This check is used to ensure documentation can be built from the main branch.
name: Check Documentation

on:
  # This workflow is only defined here. It is triggered from other workflows.
  workflow_call:

  # Allow debugging the CI/CD pipeline by running the workflow on push events
  # targeting the `cicd/develop` branch.
  push:
    branches: [cicd/develop]

jobs:
  test_documentation:
    name: Test the documenation build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup system cached
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: git cmake doxygen graphviz
          version: 1.0

      - name: Build documentation
        run: |
          cmake -DONLY_DOCS=ON -B build -S .
          cmake --build build --target documentation
