# This workflow checks the compilation of the Neko-TOP library.

name: Check Neko-TOP compilation

# This workflow is only defined here. It is triggered from other workflows.
on:
  workflow_call:
    inputs:
      neko-version:
        description: "The version of Neko to use."
        required: true
        type: string
      json-fortran-version:
        description: "The version of json-fortran to use."
        required: true
        type: string
      pfunit-version:
        description: "The version of pFUnit to use."
        required: true
        type: string

# ---------------------------------------------------------------------------- #
# Define the jobs that will be run in this workflow. The jobs are run in a

jobs:

  # -------------------------------------------------------------------------- #
  # Define the compilation and testing job that will be run in this workflow.
  # This job will build the Neko-TOP code in debug mode and run the unit tests.

  neko-top-debug:

    # ------------------------------------------------------------------------ #
    # Define the Matrix for the job.
    # ------------------------------------------------------------------------ #

    strategy:
      fail-fast: false
      matrix:

        # Minimal matrix for debugging
        os: [ubuntu-latest]
        precision: [dp, sp]
        compiler: [gfortran-13]
        backend: [cuda]

        # Full matrix
        # os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest]
        # precision: [sp, dp]
        # compiler: [gfortran-12, gfortran-13, gfortran-14]
        # backend: [cpu, cuda, hip, opencl]

        # Define the setup jobs
        include:
          - os: ubuntu-latest
            setup-env: |
              sudo apt-get update
              sudo apt-get install -y libopenblas-dev libopenmpi-dev \
                openmpi-bin pkg-config liblapack-dev ninja-build

          - backend: cuda
            os: ubuntu-latest
            precision: sp
            setup-backend: |
              sudo apt-get update
              sudo apt-get install -y nvidia-cuda-toolkit
              echo "backend-path=/usr" >> $GITHUB_OUTPUT

    # ------------------------------------------------------------------------ #
    # Define the job itself.
    # ------------------------------------------------------------------------ #
    name: ${{matrix.os}} - ${{matrix.precision}} - ${{matrix.compiler}} - ${{matrix.backend}}
    runs-on: ${{matrix.os}}

    steps:
      # ---------------------------------------------------------------------- #
      # Checkout the repository and setup the environment
      # ---------------------------------------------------------------------- #

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup non-cache dependencies
        shell: bash
        run: ${{ matrix.setup-env }}

      - name: Setup backend
        id: setup-backend
        shell: bash
        run: ${{ matrix.setup-backend }}

      # ---------------------------------------------------------------------- #
      # Setup the external dependencies
      # ---------------------------------------------------------------------- #

      - name: Get json-fortran
        id: get-json-fortran
        uses: ./.github/actions/setup_json-fortran
        with:
          version: ${{ inputs.json-fortran-version }}

      - name: Get neko
        id: get-neko
        uses: ./.github/actions/setup_neko
        with:
          json-fortran-dir: ${{ steps.get-json-fortran.outputs.install-dir }}
          version: ${{ inputs.neko-version }}
          precision: ${{ matrix.precision }}
          os: ${{ matrix.os }}
          compiler: ${{ matrix.compiler }}
          backend: ${{ matrix.backend }}
          backend-path: ${{ steps.setup-backend.outputs.backend-path }}


      - name: Get pfunit
        id: get-pfunit
        uses: ./.github/actions/setup_pfunit
        with:
          version: ${{ inputs.pfunit-version }}

      # ---------------------------------------------------------------------- #
      # Build and test the code
      # ---------------------------------------------------------------------- #

      - name: Configuration
        env:
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          PFUNIT_DIR: ${{ steps.get-pfunit.outputs.install-dir }}
        run: |
          cmake -B build -S . -G Ninja --fresh \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_Fortran_COMPILER=${{ matrix.compiler }} \
            -DBUILD_TESTING=ON

      - name: Building Library
        run: |
          cmake --build build --parallel

      # ---------------------------------------------------------------------- #
      # Run the tests, which is only done on the CPU backend as the github
      # runner does not have a GPU available.
      # ---------------------------------------------------------------------- #

      - name: Running Unit Tests
        if: ${{ matrix.backend == 'cpu' }}
        run: |
          ctest --test-dir build --output-on-failure --parallel -L "Unit"

      - name: Building Examples
        run: |
          cmake --build build --target Examples --parallel

      - name: Run Rugby Ball
        if: ${{ matrix.backend == 'cpu' }}
        env:
          NEKO_DIR: ${{ steps.get-neko.outputs.install-dir }}
          JSON_FORTRAN_DIR: ${{ steps.get-json-fortran.outputs.install-dir }}
        run: |
          # Adjust the end time and max iterations for the rugby ball case
          sed -i -r 's/"end_time":.*/"end_time": 1e-3,/g' examples/rugby_ball/rugby_ball.case
          sed -i -r 's/"max_iterations":.*/"max_iterations": 2,/g' examples/rugby_ball/rugby_ball.case

          ./run.sh -rc rugby_ball

      # ---------------------------------------------------------------------- #
      # Report errors if any step fails
      # ---------------------------------------------------------------------- #
      - name: Report errors
        if: failure()
        run: |
          echo "Errors encountered during script execution."
          ëcho "Please check the logs for details."
          logs=($(find logs/ -name "error.log" 2>/dev/null))

          for file in ${logs[@]}; do
            if [[ -s $file ]]; then
              printf "\nContents of $file:\n" >&2
              cat $file >&2
            elif [ -f $file ]; then
              rm -fr $(dirname $file)
            fi
          done

      - name: Save logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: check-compile-logs
          path: logs/**/*.log
          overwrite: true
