# This check is used to ensure documentation can be built from the main branch.
name: Check Formatting

on: [workflow_call]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: '**/requirements-formatting.txt'

      - name: Install findent
        run: |
          pip install -r .github/workflows/extra/requirements-formatting.txt

      - name: Format sources
        env:
          FINDENT_FLAGS: ${{ vars.FINDENT_FLAGS }}
        run: |
          find sources/ -name "*.f90" -type f -exec bash -c \
            "findent < \"{}\" > \"{}\".tmp && mv -f \"{}\".tmp \"{}\"" \;

      - name: Check format
        run: |
          git diff --exit-code
