name: Deploy documentation to Pages

# Runs on every push to the develop branch. Since the develop branch is
# protected, only pull requests can be merged into it. This ensures that the
# documentation is only built and deployed when a pull request is merged.
on:
  workflow_call:
  push:
    branches:
      - "develop"

jobs:
  documentation:
    name: Build and deploy documentation

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Setup system
        shell: bash
        run: |
          sudo apt install git cmake doxygen graphviz

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure documentation
        run: |
          cmake -DONLY_DOCS=ON -B build -S . -DCMAKE_BUILD_TYPE=Release

      - name: Build documentation
        run: |
          cmake --build build --target Documentation

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        id: deployment
        uses: actions/deploy-pages@v4
