name: Documentation

# Runs on every push to the develop branch. Since the develop branch is
# protected, only pull requests can be merged into it. This ensures that the
# documentation is only built and deployed when a pull request is merged.
on:
  workflow_call:
  workflow_dispatch:

jobs:
  # -------------------------------------------------------------------------- #
  # Build Documentation job

  build-docs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Create cache key based on commit SHA
        id: create-key
        shell: bash
        run: |
          # Get the GIT sha for the current commit
          key="documentation-$(git rev-parse HEAD)"
          printf "key=%s\n" "$key" | tee -a $GITHUB_OUTPUT

      - name: Create cache the documentation
        id: cache-documentation
        uses: actions/cache@v5
        with:
          path: documentation/html/
          key: ${{ steps.create-key.outputs.key }}

      - name: Setup system
        if: steps.cache-documentation.outputs.cache-hit != 'true'
        run: sudo apt install git cmake doxygen graphviz

      - name: Configure
        if: steps.cache-documentation.outputs.cache-hit != 'true'
        run: cmake -DONLY_DOCS=ON -B build -S .

      - name: Build
        if: steps.cache-documentation.outputs.cache-hit != 'true'
        run: cmake --build build --target Documentation

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v5
        with:
          path: documentation/html/

  # -------------------------------------------------------------------------- #
  # Deploy documentation job

  deploy-docs:
    name: Deploy
    runs-on: ubuntu-latest

    if: github.event_name == 'push'
    needs: build-docs

    # Define the deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

      # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    # Define the deployment strategy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
