name: Check Pull Requests onto develop

on:
  pull_request:
    branches:
      - develop

jobs:
  is_draft:
    if: github.event.pull_request.draft == true

    name: Check if PR is a draft
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is a draft
        run: echo "This PR is a draft"

  check_formatting:
    if: github.event.pull_request.draft != true

    name: Formatting
    needs: is_draft
    uses: ./.github/workflows/check_formatting.yml

  check_compilation:
    if: github.event.pull_request.draft != true

    name: Compilation
    uses: ./.github/workflows/check_neko-top.yml

    with:
      neko-version: "develop"

  check_complete:
    if: github.event.pull_request.draft != true

    name: Complete Develop PR Checks
    needs:
      - check_formatting
      - check_compilation

    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All checks passed"
