name: Main Checks

on:
  pull_request:
    branches: [main]

jobs:
  check_formatting:
    name: Formatting
    uses: ./.github/workflows/check_formatting.yml

  check_documentation:
    name: Documentation
    uses: ./.github/workflows/check_documentation.yml

  check_compilation:
    name: Compilation
    uses: ./.github/workflows/check_neko-top.yml
    with:
      neko-version: "master"

  check_complete:
    name: Main Checks
    needs:
      - check_formatting
      - check_documentation
      - check_compilation

    runs-on: ubuntu-latest
    env:
      check_formatting: ${{ needs.check_formatting.result }}
      check_documentation: ${{ needs.check_documentation.result }}
      check_compilation: ${{ needs.check_compilation.result }}

    steps:
      - name: All checks passed
        run: |
          if [ "$check_formatting" != "success" ]; then
            echo "Formatting check failed"
            exit 1
          elif [ "$check_compilation" != "success" ]; then
            echo "Compilation check failed"
            exit 1
          fi
          echo "All checks passed"
