name: Main Checks

on:
  pull_request:
    branches: [main]

jobs:
  check_formatting:
    name: Formatting
    uses: ./.github/workflows/check_formatting.yml

  check_documentation:
    name: Documentation
    uses: ./.github/workflows/check_documentation.yml

  check_compilation:
    name: Compilation
    uses: ./.github/workflows/check_neko-top.yml
    with:
      neko-version: "master"

  check_complete:
    name: Main Checks
    needs:
      - check_formatting
      - check_documentation
      - check_compilation
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All checks passed"
